services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env.base
      - ./client/.env.${ENV}
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env.base
      - ./server/.env.${ENV}
    secrets:
      - db_password
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
  db:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    secrets:
      - db_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - shredders-db:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server"]
    volumes:
      - db-cache:/data

secrets:
  db_password:
    file: db_password_${ENV}.txt

volumes:
  shredders-db:
  db-cache: