name: Deploy to Render
on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      # Clone the repo to the runner
      - uses: actions/checkout@v4

      - name: test
        run: |
          npm install
          npm run test
      
      - name: build
        run: |
          npm run build
    
      - name: deploy
        # Only run if on main branch
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
